
[build]
  publish = "_site"
  command = "npm run build:ci"

[build.environment]
  ELEVENTY_ENV = "prod"

[build.processing]
  skip_processing = true

[[headers]]

 for = "/*"
 [headers.values]
   X-Frame-Options = "DENY"
   X-XSS-Protection = "1; mode=block"
   X-Content-Type-Options = "nosniff"
   Referrer-Policy= "strict-origin-when-cross-origin"
