
[build]
  publish = "_site"

[build.processing]
[build.processing.html]
  pretty_urls = true

[[headers]]

 for = "/*"
 [headers.values]
   X-Frame-Options = "DENY"
   X-XSS-Protection = "1; mode=block"
   X-Content-Type-Options = "nosniff"
   Referrer-Policy= "strict-origin-when-cross-origin"
