
[build]
  publish = "_site"
  command = "npm run build:ci"

[build.environment]
  ELEVENTY_ENV = "prod"

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy= "strict-origin-when-cross-origin"
    Report-To = '{"group":"csp-endpoint","max_age":10886400,"endpoints":[{"url":"https://o4506961019011072.ingest.sentry.io/api/4506961300553728/security/?sentry_key=41f49691265f08a71261ecdf84fe8ec5"}],"include_subdomains":true}'
    Content-Security-Policy-Report-Only = "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'; frame-ancestors 'none'; report-uri https://o4506961019011072.ingest.sentry.io/api/4506961300553728/security/?sentry_key=41f49691265f08a71261ecdf84fe8ec5; report-to csp-endpoint"




